Vagrant::Config.run do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "lucid32"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://files.vagrantup.com/lucid32.box"

  # config.vm.customize do |vm|
  #   vm.name = "Wise4-trunk"
  #   vm.memory_size = 512
  # end
  config.vm.customize ["modifyvm", :id, "--memory", "512"]
  config.vm.customize ["modifyvm", :id, "--name",   "Wise4-trunk"]
  # the port forwarded from the host machine
  wise4_port=8080

  # enable this so we can install the extensions
  # config.vm.boot_mode = :gui

  # Assign this VM to a host only network IP, allowing you to access it
  # via the IP.
  config.vm.network :hostonly, "33.33.33.10"

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  # NOTE: this port 8080 is hard coded into some of the wise4 settings files
  #   so changing it might break somethings. 
  config.vm.forward_port 8080, 8080


  # Enable provisioning with chef solo, specifying a cookbooks path (relative
  # to this Vagrantfile), and adding some recipes and/or roles.
  #
  # config.vm.provision :chef_solo do |chef|
  #   chef.cookbooks_path = "cookbooks"
  #   chef.add_recipe "mysql"
  #   chef.add_role "web"
  #
  #   
  #   chef.json = { :mysql_password => "foo" }
  # end
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "cookbooks"

    # Tell chef what recipe to run. In this case, the `vagrant_main` recipe
    # does all the magic.
    chef.add_recipe("vagrant_main")

    # Customize recipes
    chef.json.merge!({ 
      :tomcat => {:java_options => "-Xms128m -Xmx256m -XX:PermSize=128m -XX:MaxPermSize=256m"},
      :mysql => {:server_root_password => "password", :bind_address => '127.0.0.1'},
      :wise4_port => wise4_port
    })

    # added to write config data for Amazon EC2 provisioning
    # see the documentation here: https://github.com/lynaghk/vagrant-ec2
    require 'json'
    open('dna.json', 'w') do |f|
      chef.json[:run_list] = chef.run_list
      f.write chef.json.to_json
    end
      open('.cookbooks_path.json', 'w') do |f|
      f.puts JSON.generate([chef.cookbooks_path]
                             .flatten
                             .map{|x| File.expand_path(x)})
    end

  end
end
